const config = {
  apiEndpoint: 'http://localhost:5100',
}

export const surveyJson = {
  logoPosition: 'right',
  pages: [
    {
      name: 'page1',
      elements: [
        {
          type: 'panel',
          name: 'generalPanel',
          elements: [
            {
              type: 'radiogroup',
              name: 'profileType',
              startWithNewLine: false,
              title: ' ',
              titleLocation: 'hidden',
              hideNumber: true,
              defaultValue: 'company',
              choices: [
                {
                  value: 'company',
                  text: 'นิติบุคคล',
                },
                {
                  value: 'individual',
                  text: 'บุคคลธรรมดา',
                },
              ],
              colCount: 0,
            },
            {
              type: 'text',
              name: 'taxId',
              visibleIf: "{profileType} = 'company'",
              clearIfInvisible: 'onComplete',
              title: 'เลขทะเบียนนิติบุคคล',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'company'",
              requiredErrorText: 'กรุณากรอกเลขทะเบียนนิติบุคคล',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเลขทะเบียนนิติบุคคลไม่ถูกต้อง',
                  regex: '^(\\d{13})?$',
                },
              ],
              maxLength: 13,
              placeholder: 'เลขทะเบียนนิติบุคคล',
            },
            {
              type: 'text',
              name: 'name',
              visibleIf: "{profileType} = 'company'",
              clearIfInvisible: 'onComplete',
              startWithNewLine: false,
              title: 'ชื่อนิติบุคคล',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'company'",
              requiredErrorText: 'กรุณากรอกชื่อนิติบุคคล',
              maxLength: 100,
              placeholder: 'ชื่อนิติบุคคล',
            },
            {
              type: 'text',
              name: 'idNo',
              visibleIf: "{profileType} = 'individual'",
              clearIfInvisible: 'onComplete',
              title: 'เลขบัตรประชาชน',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'individual'",
              requiredErrorText: 'กรุณากรอกเลขบัตรประชาชน',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเลขบัตรประชาชนไม่ถูกต้อง',
                  regex: '^(\\d{13})?$',
                },
              ],
              maxLength: 13,
              placeholder: 'กรุณากรอกเลขบัตรประชาชน 13 หลัก',
            },
            {
              type: 'dropdown',
              name: 'title',
              visibleIf: "{profileType} = 'individual'",
              clearIfInvisible: 'onComplete',
              width: '20%',
              minWidth: '200px',
              title: 'คำนำหน้า',
              placeholder: 'คำนำหน้า',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'individual'",
              requiredErrorText: 'กรุณาระบุคำนำหน้า',
              choicesByUrl: {
                url: `${config.apiEndpoint}/api/v1/master/lov/title`,
                path: 'data',
                valueName: 'key',
                titleName: 'label',
              },
              allowClear: false,
            },
            {
              type: 'text',
              name: 'firstname',
              visibleIf: "{profileType} = 'individual'",
              clearIfInvisible: 'onComplete',
              width: '30%',
              startWithNewLine: false,
              title: 'ชื่อ',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'individual'",
              requiredErrorText: 'กรุณากรอกชื่อ',
              maxLength: 100,
              placeholder: 'ชื่อ',
            },
            {
              type: 'text',
              name: 'lastname',
              visibleIf: "{profileType} = 'individual'",
              clearIfInvisible: 'onComplete',
              width: '50%',
              startWithNewLine: false,
              title: 'นามสกุล',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'individual'",
              requiredErrorText: 'กรุณากรอกนามสกุล',
              maxLength: 100,
              placeholder: 'นามสกุล',
            },
            {
              type: 'text',
              name: 'telephone',
              title: 'เบอร์โทรศัพท์',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกเบอร์โทรศัพท์',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง',
                  regex: '^0\\d{8,9}$',
                },
              ],
              inputType: 'tel',
              placeholder: 'เบอร์โทรศัพท์',
              maxLength: 10,
            },
            {
              type: 'text',
              name: 'email',
              startWithNewLine: false,
              title: 'อีเมล',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกอีเมล',
              validators: [
                {
                  type: 'email',
                  text: 'รูปแบบอีเมลไม่ถูกต้อง',
                },
              ],
              inputType: 'email',
              maxLength: 100,
              placeholder: 'อีเมล',
            },
          ],
          title: 'ข้อมูลทั่วไป',
        },
        {
          type: 'panel',
          name: 'addressPanel',
          elements: [
            {
              type: 'text',
              name: 'address',
              startWithNewLine: false,
              title: 'ที่อยู่ (Address)',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกที่อยู่',
              maxLength: 200,
              placeholder: 'เลขที่บ้าน, ซอย, ถนน, ...',
            },
            {
              type: 'dropdown',
              name: 'province',
              width: '30%',
              startWithNewLine: true,
              title: 'จังหวัด (Province)',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกจังหวัด',
              choicesByUrl: {
                url: `${config.apiEndpoint}/api/v1/master/addresses/province`,
                path: 'data',
                valueName: 'key',
                titleName: 'label',
              },
              choicesOrder: 'asc',
              placeholder: 'จังหวัด',
              allowClear: false,
            },
            {
              type: 'dropdown',
              name: 'district',

              startWithNewLine: false,
              title: 'อำเภอ (District)',
              hideNumber: true,
              isRequired: true,
              enableIf: '{provinceSet}',
              requiredErrorText: 'กรุณากรอกอำเภอ',
              choicesByUrl: {
                url: `${config.apiEndpoint}/api/v1/master/addresses/district?provinceCode={province}`,
                path: 'data',
                valueName: 'key',
                titleName: 'label',
              },
              choicesOrder: 'asc',
              placeholder: 'อำเภอ',
              allowClear: false,
            },
            {
              type: 'dropdown',
              name: 'subdistrict',

              startWithNewLine: false,
              title: 'ตำบล (Sub-District)',
              hideNumber: true,
              enableIf: '{provinceSet} and {districtSet}',
              isRequired: true,
              requiredErrorText: 'กรุณากรอกตำบล',
              choicesByUrl: {
                url: `${config.apiEndpoint}/api/v1/master/addresses/subdistrict?provinceCode={province}&districtCode={district}`,
                path: 'data',
                valueName: 'key',
                titleName: 'label',
              },
              choicesOrder: 'asc',
              placeholder: 'ตำบล',
              allowClear: false,
            },
            {
              type: 'dropdown',
              name: 'zipcode',
              width: '30%',
              startWithNewLine: false,
              title: 'รหัสไปรษณีย์ (Zipcode)',
              hideNumber: true,
              enableIf: '{provinceSet} and {districtSet} and {subdistrictSet}',
              isRequired: true,
              requiredErrorText: 'กรุณากรอกรหัสไปรษณีย์',
              choicesByUrl: {
                url: `${config.apiEndpoint}/api/v1/master/addresses/zipcode?provinceCode={province}&districtCode={district}&subdistrictCode={subdistrict}`,
                path: 'data',
                valueName: 'key',
                titleName: 'label',
              },
              choicesOrder: 'asc',
              placeholder: 'รหัสไปรษณีย์',
              allowClear: false,
            },
          ],
          title: '{addressTitle}',
        },
        {
          type: 'panel',
          name: 'contactPanel',
          elements: [
            {
              type: 'dropdown',
              name: 'contactTitle',
              width: '20%',
              minWidth: '200px',
              title: 'คำนำหน้า',
              placeholder: 'คำนำหน้า',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณาระบุคำนำหน้า',
              choicesFromQuestion: 'title',
              allowClear: false,
            },
            {
              type: 'text',
              name: 'contactFirstname',
              width: '30%',
              startWithNewLine: false,
              title: 'ชื่อ',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกชื่อ',
              maxLength: 100,
              placeholder: 'ชื่อ',
            },
            {
              type: 'text',
              name: 'contactLastname',
              width: '50%',
              startWithNewLine: false,
              title: 'นามสกุล',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกนามสกุล',
              maxLength: 100,
              placeholder: 'นามสกุล',
            },
            {
              type: 'text',
              name: 'contactTelephone',
              title: 'เบอร์โทรศัพท์',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกเบอร์โทรศัพท์',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง',
                  regex: '^0\\d{8,9}$',
                },
              ],
              inputType: 'tel',
              placeholder: 'เบอร์โทรศัพท์',
              maxLength: 10,
            },
            {
              type: 'text',
              name: 'contactEmail',
              startWithNewLine: false,
              title: 'อีเมล',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกอีเมล',
              validators: [
                {
                  type: 'email',
                  text: 'รูปแบบอีเมลไม่ถูกต้อง',
                },
              ],
              inputType: 'email',
              maxLength: 100,
              placeholder: 'อีเมล',
            },
          ],
          visibleIf: "{profileType} = 'company'",
          clearIfInvisible: 'onComplete',
          title: 'ข้อมูลผู้ติดต่อ',
        },
        {
          type: 'panel',
          name: 'membershipPanel',
          elements: [
            {
              type: 'radiogroup',
              name: 'membership',
              startWithNewLine: false,
              title: ' ',
              hideNumber: true,
              choices: ['ใช่', 'ไม่ใช่'],
            },
            {
              type: 'html',
              name: 'isMemberShip',
              html: '<div>ท่านสามารถสมัครเป็นสมาชิกของหอการค้าไทยฯ ประเภท Pre-Member ฟรี ไม่เสียค่าใช้จ่าย ได้ที่ลิงก์นี้ <a href="https://register.thaichamber.org/question/514" target="_blank" style="color: #0086C9; text-decoration: underline; overflow-wrap: break-word;" >https://register.thaichamber.org/question/514</a></div>',
            },
          ],
          title: 'ท่านเป็นสมาชิกของหอการค้าไทยและสภาหอการค้าแห่งประเทศไทยหรือไม่',
          isRequired: true,
        },
        {
          type: 'dropdown',
          name: 'country',
          title: 'Select a country',
          isRequired: true,
          defaultValue: 'FRA',
          choicesLazyLoadEnabled: true,
          choicesLazyLoadPageSize: 40,
        },
      ],
      title: 'headerTitle',
    },
  ],
  calculatedValues: [
    {
      name: 'addressTitle',
      expression: "iif({profileType} = 'company', 'ที่อยู่บริษัท', 'ที่อยู่')",
    },
  ],
  showQuestionNumbers: 'off',
  questionErrorLocation: 'bottom',
  completeText: 'fff',
  showCompletedPage: false,
}
