export const jsonSuperSurvey = {
  name: 'Personal Information',
  elements: [
    {
      type: 'panel',
      name: 'generalPanel',
      elements: [
        {
          type: 'panel',
          name: 'uploadPanel',
          elements: [
            {
              type: 'file',
              name: 'images',
              title:
                'กรุณาอัปโหลด รูปภาพด้านหน้า ด้านข้าง ด้านหลังของสินค้า โดยท่านสามารถอัปโหลดรูปภาพได้สูงสุดไม่เกิน 5 รูป',
              description: 'ประเภทไฟล์ .jpg, .jpeg, .png (ขนาดรูปไม่เกิน 1 MB)',
              hideNumber: true,
              isRequired: true,
              showPreview: true,
              requiredErrorText: 'กรุณาอัปโหลดรูปภาพ',
              allowMultiple: true,
              acceptedTypes: 'image/png, image/jpeg',
              storeDataAsText: false,
              waitForUpload: true,
              maxSize: 1048576,
              needConfirmRemoveFile: true,
              custom: {
                maxFiles: 2,
                maxTotalFileSize: 10240000,
                maxFilesErrorText: 'maxFilesErrorText (from json)', // This works but it duplicates in every survey
                enableZoomInModal: true,
                modalMaxWidth: 700,
                // TODO
                // DISCUSS: don't want this for localization.
                // maxFilesErrorText: {
                //   en: '',
                //   th: '',
                // },
                // (1) Maybe try to do this
                // maxFilesErrorText: t('common:error.maxFiles'))
                // (2) or
                // maxFilesErrorText: 'common:error.maxFiles'
                // (3) set in code
              },
            },
          ],
          title: 'อัปโหลดรูปภาพ',
        },
        {
          type: 'text',
          name: 'idNo',
          clearIfInvisible: 'onComplete',
          title: 'เลขบัตรประชาชน',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกเลขบัตรประชาชน',
          validators: [
            {
              type: 'regex',
              text: 'รูปแบบเลขบัตรประชาชนไม่ถูกต้อง',
              regex: '^(\\d{13})?$',
            },
          ],
          maxLength: 13,
          placeholder: 'กรุณากรอกเลขบัตรประชาชน 13 หลัก',
        },
        {
          type: 'radiogroup',
          name: 'membership',
          title: 'เพศ',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณาเลือกเพศ',
          choices: ['ชาย', 'หญิง', 'อื่นๆ'],
        },
        {
          type: 'dropdown',
          name: 'title',
          clearIfInvisible: 'onComplete',
          width: '20%',
          minWidth: '200px',
          title: 'คำนำหน้า',
          placeholder: 'คำนำหน้า',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณาระบุคำนำหน้า',
          allowClear: false,
          choices: [
            {
              value: 'mr',
              text: 'นาย',
            },
            {
              value: 'mrs',
              text: 'นาง',
            },
            {
              value: 'ms',
              text: 'นางสาว',
            },
          ],
        },
        {
          type: 'text',
          name: 'firstname',
          clearIfInvisible: 'onComplete',
          width: '30%',
          startWithNewLine: false,
          title: 'ชื่อ',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกชื่อ',
          maxLength: 100,
          placeholder: 'ชื่อ',
        },
        {
          type: 'text',
          name: 'lastname',
          clearIfInvisible: 'onComplete',
          width: '50%',
          startWithNewLine: false,
          title: 'นามสกุล',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกนามสกุล',
          maxLength: 100,
          placeholder: 'นามสกุล',
        },
        {
          type: 'text',
          name: 'telephone',
          title: 'เบอร์โทรศัพท์',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกเบอร์โทรศัพท์',
          validators: [
            {
              type: 'regex',
              text: 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง',
              regex: '^0\\d{8,9}$',
            },
          ],
          inputType: 'tel',
          placeholder: 'เบอร์โทรศัพท์',
          maxLength: 10,
        },
        {
          type: 'text',
          name: 'email',
          startWithNewLine: false,
          title: 'อีเมล',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกอีเมล',
          validators: [
            {
              type: 'email',
              text: 'รูปแบบอีเมลไม่ถูกต้อง',
            },
          ],
          inputType: 'email',
          maxLength: 100,
          placeholder: 'อีเมล',
        },
        {
          type: 'checkbox',
          name: 'car',
          title: 'รถ',
          choices: [
            'Ford',
            'Vauxhall',
            'Volkswagen',
            'Nissan',
            'Audi',
            'Mercedes-Benz',
            'BMW',
            'Peugeot',
            'Toyota',
            'Citroen',
          ],
          isRequired: true,
          hideNumber: true,
          colCount: 2,
          showNoneItem: true,
          showOtherItem: true,
          showSelectAllItem: true,
          separateSpecialChoices: true,
        },
      ],
      title: 'ข้อมูลทั่วไป',
    },
    {
      type: 'panel',
      name: 'addressPanel',
      elements: [
        {
          type: 'text',
          name: 'address',
          startWithNewLine: false,
          title: 'ที่อยู่ (Address)',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกที่อยู่',
          maxLength: 200,
          placeholder: 'เลขที่บ้าน, ซอย, ถนน, ...',
        },
        {
          type: 'dropdown',
          name: 'province',
          width: '30%',
          startWithNewLine: true,
          title: 'จังหวัด (Province)',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกจังหวัด',
          choicesLazyLoadEnabled: true,
        },
        {
          type: 'dropdown',
          name: 'district',
          startWithNewLine: false,
          title: 'อำเภอ (District)',
          hideNumber: true,
          isRequired: true,
          enableIf: '{province} notempty',
          requiredErrorText: 'กรุณากรอกอำเภอ',
          choicesLazyLoadEnabled: true,
        },
        {
          type: 'dropdown',
          name: 'subdistrict',
          startWithNewLine: false,
          title: 'ตำบล (Sub-District)',
          hideNumber: true,
          isRequired: true,
          requiredErrorText: 'กรุณากรอกตำบล',
          enableIf: '{province} notempty and {district} notempty',
          choicesLazyLoadEnabled: true,
        },
        {
          type: 'dropdown',
          name: 'zipcode',
          width: '30%',
          startWithNewLine: false,
          title: 'รหัสไปรษณีย์ (Zipcode)',
          hideNumber: true,
          enableIf: '{province} notempty and {district} notempty and {subdistrict} notempty',
          isRequired: true,
          requiredErrorText: 'กรุณากรอกรหัสไปรษณีย์',
          choicesLazyLoadEnabled: true,
        },
      ],
      title: 'ที่อยู่',
    },
  ],
  title: 'Personal Information',
}
