// test survey js models
export const surveyJson = {
  logoPosition: 'right',
  pages: [
    {
      name: 'Personal Information',
      elements: [
        {
          type: 'panel',
          name: 'generalPanel',
          elements: [
            {
              type: 'radiogroup',
              name: 'profileType',
              startWithNewLine: false,
              title: ' ',
              titleLocation: 'hidden',
              hideNumber: true,
              defaultValue: 'company',
              choices: [
                {
                  value: 'company',
                  text: 'นิติบุคคล',
                },
                {
                  value: 'individual',
                  text: 'บุคคลธรรมดา',
                },
              ],
              colCount: 0,
            },
            {
              type: 'text',
              name: 'taxId',
              visibleIf: "{profileType} = 'company'",
              clearIfInvisible: 'onComplete',
              title: 'เลขทะเบียนนิติบุคคล',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'company'",
              requiredErrorText: 'กรุณากรอกเลขทะเบียนนิติบุคคล',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเลขทะเบียนนิติบุคคลไม่ถูกต้อง',
                  regex: '^(\\d{13})?$',
                },
              ],
              maxLength: 13,
              placeholder: 'เลขทะเบียนนิติบุคคล',
            },
            {
              type: 'text',
              name: 'name',
              visibleIf: "{profileType} = 'company'",
              clearIfInvisible: 'onComplete',
              startWithNewLine: false,
              title: 'ชื่อนิติบุคคล',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'company'",
              requiredErrorText: 'กรุณากรอกชื่อนิติบุคคล',
              maxLength: 100,
              placeholder: 'ชื่อนิติบุคคล',
            },
            {
              type: 'text',
              name: 'idNo',
              visibleIf: "{profileType} = 'individual'",
              clearIfInvisible: 'onComplete',
              title: 'เลขบัตรประชาชน',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'individual'",
              requiredErrorText: 'กรุณากรอกเลขบัตรประชาชน',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเลขบัตรประชาชนไม่ถูกต้อง',
                  regex: '^(\\d{13})?$',
                },
              ],
              maxLength: 13,
              placeholder: 'กรุณากรอกเลขบัตรประชาชน 13 หลัก',
            },
            // {
            //   type: 'dropdown',
            //   name: 'title',
            //   visibleIf: "{profileType} = 'individual'",
            //   clearIfInvisible: 'onComplete',
            //   width: '20%',
            //   minWidth: '200px',
            //   title: 'คำนำหน้า',
            //   placeholder: 'คำนำหน้า',
            //   hideNumber: true,
            //   isRequired: true,
            //   requiredIf: "{profileType} = 'individual'",
            //   requiredErrorText: 'กรุณาระบุคำนำหน้า',
            //   choicesByUrl: {
            //     url: `${config.apiEndpoint}/api/v1/master/lov/title`,
            //     path: 'data',
            //     valueName: 'key',
            //     titleName: 'label',
            //   },
            //   allowClear: false,
            // },
            {
              type: 'text',
              name: 'firstname',
              visibleIf: "{profileType} = 'individual'",
              clearIfInvisible: 'onComplete',
              width: '30%',
              startWithNewLine: false,
              title: 'ชื่อ',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'individual'",
              requiredErrorText: 'กรุณากรอกชื่อ',
              maxLength: 100,
              placeholder: 'ชื่อ',
            },
            {
              type: 'text',
              name: 'lastname',
              visibleIf: "{profileType} = 'individual'",
              clearIfInvisible: 'onComplete',
              width: '50%',
              startWithNewLine: false,
              title: 'นามสกุล',
              hideNumber: true,
              isRequired: true,
              requiredIf: "{profileType} = 'individual'",
              requiredErrorText: 'กรุณากรอกนามสกุล',
              maxLength: 100,
              placeholder: 'นามสกุล',
            },
            {
              type: 'text',
              name: 'telephone',
              title: 'เบอร์โทรศัพท์',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกเบอร์โทรศัพท์',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง',
                  regex: '^0\\d{8,9}$',
                },
              ],
              inputType: 'tel',
              placeholder: 'เบอร์โทรศัพท์',
              maxLength: 10,
            },
            {
              type: 'text',
              name: 'email',
              startWithNewLine: false,
              title: 'อีเมล',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกอีเมล',
              validators: [
                {
                  type: 'email',
                  text: 'รูปแบบอีเมลไม่ถูกต้อง',
                },
              ],
              inputType: 'email',
              maxLength: 100,
              placeholder: 'อีเมล',
            },
          ],
          title: 'ข้อมูลทั่วไป',
        },
        // {
        //   type: 'panel',
        //   name: 'addressPanel',
        //   elements: [
        //     {
        //       type: 'text',
        //       name: 'address',
        //       startWithNewLine: false,
        //       title: 'ที่อยู่ (Address)',
        //       hideNumber: true,
        //       isRequired: true,
        //       requiredErrorText: 'กรุณากรอกที่อยู่',
        //       maxLength: 200,
        //       placeholder: 'เลขที่บ้าน, ซอย, ถนน, ...',
        //     },
        //     {
        //       type: 'dropdown',
        //       name: 'province',
        //       width: '30%',
        //       startWithNewLine: true,
        //       title: 'จังหวัด (Province)',
        //       hideNumber: true,
        //       isRequired: true,
        //       requiredErrorText: 'กรุณากรอกจังหวัด',
        //       choicesByUrl: {
        //         url: `${config.apiEndpoint}/api/v1/master/addresses/province`,
        //         path: 'data',
        //         valueName: 'key',
        //         titleName: 'label',
        //       },
        //       choicesOrder: 'asc',
        //       placeholder: 'จังหวัด',
        //       allowClear: false,
        //     },
        //     {
        //       type: 'dropdown',
        //       name: 'district',

        //       startWithNewLine: false,
        //       title: 'อำเภอ (District)',
        //       hideNumber: true,
        //       isRequired: true,
        //       enableIf: '{provinceSet}',
        //       requiredErrorText: 'กรุณากรอกอำเภอ',
        //       choicesByUrl: {
        //         url: `${config.apiEndpoint}/api/v1/master/addresses/district?provinceCode={province}`,
        //         path: 'data',
        //         valueName: 'key',
        //         titleName: 'label',
        //       },
        //       choicesOrder: 'asc',
        //       placeholder: 'อำเภอ',
        //       allowClear: false,
        //     },
        //     {
        //       type: 'dropdown',
        //       name: 'subdistrict',

        //       startWithNewLine: false,
        //       title: 'ตำบล (Sub-District)',
        //       hideNumber: true,
        //       enableIf: '{provinceSet} and {districtSet}',
        //       isRequired: true,
        //       requiredErrorText: 'กรุณากรอกตำบล',
        //       choicesByUrl: {
        //         url: `${config.apiEndpoint}/api/v1/master/addresses/subdistrict?provinceCode={province}&districtCode={district}`,
        //         path: 'data',
        //         valueName: 'key',
        //         titleName: 'label',
        //       },
        //       choicesOrder: 'asc',
        //       placeholder: 'ตำบล',
        //       allowClear: false,
        //     },
        //     {
        //       type: 'dropdown',
        //       name: 'zipcode',
        //       width: '30%',
        //       startWithNewLine: false,
        //       title: 'รหัสไปรษณีย์ (Zipcode)',
        //       hideNumber: true,
        //       enableIf: '{provinceSet} and {districtSet} and {subdistrictSet}',
        //       isRequired: true,
        //       requiredErrorText: 'กรุณากรอกรหัสไปรษณีย์',
        //       choicesByUrl: {
        //         url: `${config.apiEndpoint}/api/v1/master/addresses/zipcode?provinceCode={province}&districtCode={district}&subdistrictCode={subdistrict}`,
        //         path: 'data',
        //         valueName: 'key',
        //         titleName: 'label',
        //       },
        //       choicesOrder: 'asc',
        //       placeholder: 'รหัสไปรษณีย์',
        //       allowClear: false,
        //     },
        //   ],
        //   title: '{addressTitle}',
        // },
        {
          type: 'panel',
          name: 'contactPanel',
          elements: [
            // {
            //   type: 'dropdown',
            //   name: 'contactTitle',
            //   width: '20%',
            //   minWidth: '200px',
            //   title: 'คำนำหน้า',
            //   placeholder: 'คำนำหน้า',
            //   hideNumber: true,
            //   isRequired: true,
            //   requiredErrorText: 'กรุณาระบุคำนำหน้า',
            //   choicesFromQuestion: 'title',
            //   allowClear: false,
            // },
            {
              type: 'text',
              name: 'contactFirstname',
              width: '30%',
              startWithNewLine: false,
              title: 'ชื่อ',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกชื่อ',
              maxLength: 100,
              placeholder: 'ชื่อ',
            },
            {
              type: 'text',
              name: 'contactLastname',
              width: '50%',
              startWithNewLine: false,
              title: 'นามสกุล',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกนามสกุล',
              maxLength: 100,
              placeholder: 'นามสกุล',
            },
            {
              type: 'text',
              name: 'contactTelephone',
              title: 'เบอร์โทรศัพท์',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกเบอร์โทรศัพท์',
              validators: [
                {
                  type: 'regex',
                  text: 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง',
                  regex: '^0\\d{8,9}$',
                },
              ],
              inputType: 'tel',
              placeholder: 'เบอร์โทรศัพท์',
              maxLength: 10,
            },
            {
              type: 'text',
              name: 'contactEmail',
              startWithNewLine: false,
              title: 'อีเมล',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกอีเมล',
              validators: [
                {
                  type: 'email',
                  text: 'รูปแบบอีเมลไม่ถูกต้อง',
                },
              ],
              inputType: 'email',
              maxLength: 100,
              placeholder: 'อีเมล',
            },
          ],
          visibleIf: "{profileType} = 'company'",
          clearIfInvisible: 'onComplete',
          title: 'ข้อมูลผู้ติดต่อ',
        },
        {
          type: 'panel',
          name: 'membershipPanel',
          elements: [
            {
              type: 'radiogroup',
              name: 'membership',
              startWithNewLine: false,
              title: ' ',
              hideNumber: true,
              choices: ['ใช่', 'ไม่ใช่'],
            },
            {
              type: 'html',
              name: 'isMemberShip',
              html: '<div>ท่านสามารถสมัครเป็นสมาชิกของหอการค้าไทยฯ ประเภท Pre-Member ฟรี ไม่เสียค่าใช้จ่าย ได้ที่ลิงก์นี้ <a href="https://register.thaichamber.org/question/514" target="_blank" style="color: #0086C9; text-decoration: underline; overflow-wrap: break-word;" >https://register.thaichamber.org/question/514</a></div>',
            },
          ],
          title: 'ท่านเป็นสมาชิกของหอการค้าไทยและสภาหอการค้าแห่งประเทศไทยหรือไม่',
          isRequired: true,
          requiredErrorText: ' ',
        },
        // {
        //   type: 'dropdown',
        //   name: 'country',
        //   title: 'Select a country',
        //   isRequired: true,
        //   defaultValue: 'FRA',
        //   choicesLazyLoadEnabled: true,
        //   choicesLazyLoadPageSize: 40,
        // },
      ],
      title: 'Personal Information',
    },
    {
      name: 'Product Information',
      elements: [
        {
          type: 'panel',
          name: 'generalPanel',
          elements: [
            {
              type: 'text',
              name: 'pdName',
              width: '35%',
              minWidth: '200px',
              title: 'ชื่อผลิตภัณฑ์',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกชื่อผลิตภัณฑ์',
              maxLength: 100,
              placeholder: 'ชื่อผลิตภัณฑ์',
            },
            {
              type: 'text',
              name: 'brand',
              width: '35%',
              minWidth: '200px',
              startWithNewLine: false,
              title: 'ชื่อตราผลิตภัณฑ์',
              hideNumber: true,
              requiredErrorText: 'กรุณากรอกชื่อตราผลิตภัณฑ์',
              maxLength: 100,
              placeholder: 'ชื่อตราผลิตภัณฑ์',
            },
            {
              type: 'html',
              name: 'empty1',
              width: '30%',
              startWithNewLine: false,
              html: '<div class="empty-slot"></div>',
            },
          ],
          title: 'ข้อมูลสินค้า',
          showOtherItems: true,
        },
        {
          type: 'html',
          name: 'divider1',
          html: '<div class="panel-divider"></div>',
        },
        {
          type: 'panel',
          name: 'productDetailPanel',
          elements: [
            // {
            //   type: 'dropdown',
            //   name: 'category',
            //   id: 'category',
            //   width: '100%',
            //   minWidth: '200px',
            //   title: 'กลุ่มสินค้า (Main category)',
            //   hideNumber: true,
            //   isRequired: true,
            //   requiredErrorText: 'กรุณาเลือกกลุ่มสินค้า',
            //   choicesByUrl: {
            //     url: `${config.apiEndpoint}/api/v1/master/categories`,
            //     path: 'data',
            //     valueName: 'key',
            //     titleName: 'label',
            //   },
            //   placeholder: 'เลือกกลุ่มสินค้า',
            //   allowClear: false,
            // },
            // {
            //   type: 'dropdown',
            //   name: 'subcategory',
            //   width: '100%',
            //   minWidth: '200px',
            //   startWithNewLine: false,
            //   title: 'กลุ่มสินค้าย่อย 1 (Sub category 1)',
            //   hideNumber: true,
            //   enableIf: '{category} notempty',
            //   isRequired: true,
            //   requiredErrorText: 'กรุณาเลือกกลุ่มสินค้าย่อย 1',
            //   defaultValue: '',
            //   choicesByUrl: {
            //     url: `${config.apiEndpoint}/api/v1/master/categories?parent={category}`,
            //     path: 'data',
            //     valueName: 'key',
            //     titleName: 'label',
            //   },
            //   placeholder: 'เลือกกลุ่มสินค้าย่อย',
            //   allowClear: false,
            // },
            // {
            //   type: 'dropdown',
            //   name: 'subcategory2',
            //   width: '100%',
            //   minWidth: '200px',
            //   startWithNewLine: false,
            //   title: 'กลุ่มสินค้าย่อย 2 (Sub category 2)',
            //   hideNumber: true,
            //   enableIf: '{category} notempty and {subcategory} notempty',
            //   isRequired: true,
            //   requiredErrorText: 'กรุณาเลือกกลุ่มสินค้าย่อย 2',
            //   hideIfChoicesEmpty: true,
            //   choicesByUrl: {
            //     url: `${config.apiEndpoint}/api/v1/master/categories?parent={subcategory}`,
            //     path: 'data',
            //     valueName: 'key',
            //     titleName: 'label',
            //   },
            //   placeholder: 'เลือกกลุ่มสินค้าย่อย',
            //   allowClear: false,
            // },
            {
              type: 'text',
              name: 'life',
              width: '15%',
              minWidth: '100px',
              title: 'อายุผลิตภัณฑ์',
              placeholder: '0',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกอายุผลิตภัณฑ์',
              inputType: 'number',
              min: 0,
              minErrorText: 'อายุผลิตภัณฑ์ต้องมากกว่า {0}',
              maxErrorText: 'อายุผลิตภัณฑ์ต้องน้อยกว่า {0}',
            },
            {
              type: 'text',
              name: 'temperature',
              width: '15%',
              minWidth: '100px',
              startWithNewLine: false,
              title: 'อุณหภูมิจัดเก็บ ณ จุดขาย',
              placeholder: '0',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกอุณหภูมิจัดเก็บ ณ จุดขาย',
              inputType: 'number',
            },
            {
              type: 'dropdown',
              name: 'temperatureUnit',
              width: 'auto',
              minWidth: '150px',
              startWithNewLine: false,
              title: 'หน่วย',
              hideNumber: true,
              defaultValue: 'c',
              choices: [
                {
                  value: 'c',
                  text: 'องศาเซลเซียส',
                },
                {
                  value: 'f',
                  text: 'องศาฟาเรนไฮต์',
                },
              ],
              placeholder: 'หน่วย',
              allowClear: false,
            },
            {
              type: 'html',
              name: 'empty4',
              width: '20%',
              startWithNewLine: false,
              html: '<div class="empty-slot"></div>',
            },
          ],
          title: 'รายละเอียดสินค้า',
        },
        {
          type: 'html',
          name: 'divider2',
          html: '<div class="panel-divider"></div>',
        },
        {
          type: 'panel',
          name: 'packagingPanel',
          elements: [
            {
              type: 'matrixdynamic',
              name: 'packaging',
              title: ' ',
              columns: [
                {
                  name: 'productAmount',
                  title: 'จำนวนปริมาตร/น้ำหนักต่อหน่วย',
                  placeholder: '0',
                  cellType: 'text',
                  width: '22.5%',
                  inputType: 'number',
                  min: 1,
                  minErrorText: 'จำนวนปริมาตร/น้ำหนักต้องมากกว่า {0}',
                  maxErrorText: 'จำนวนปริมาตร/น้ำหนักต้องน้อยกว่า {0}',
                  requiredIf: '{row.productQtyPerContainer} > 0',
                  requiredErrorText: 'กรุณากรอกจำนวนปริมาตร/น้ำหนัก',
                },
                {
                  name: 'productUnit',
                  title: 'หน่วย',
                  cellType: 'dropdown',
                  width: '22.5%',
                  defaultValue: 'g',
                  choices: [
                    {
                      value: 'g',
                      text: 'กรัม',
                    },
                    {
                      value: 'kg',
                      text: 'กิโลกรัม',
                    },
                    {
                      value: 'ml',
                      text: 'มิลลิลิตร',
                    },
                    {
                      value: 'l',
                      text: 'ลิตร',
                    },
                    {
                      value: 'pc',
                      text: 'ชิ้น',
                    },
                  ],
                  allowClear: false,
                },
                {
                  name: 'productQtyPerContainer',
                  title: 'จำนวนชิ้น',
                  placeholder: '0',
                  cellType: 'text',
                  width: '22.5%',
                  inputType: 'number',
                  min: 1,
                  minErrorText: 'จำนวนชิ้นต้องมากกว่า {0}',
                  maxErrorText: 'จำนวนชิ้นต้องน้อยกว่า {0}',
                  requiredIf: '{row.productAmount} > 0',
                  requiredErrorText: 'กรุณากรอกจำนวนชิ้น',
                },
                {
                  name: 'containerUnit',
                  title: 'หน่วย',
                  cellType: 'dropdown',
                  width: '22.5%',
                  defaultValue: 'box',
                  choices: [
                    {
                      value: 'box',
                      text: 'ชิ้นต่อลัง',
                    },
                    {
                      value: 'pack',
                      text: 'ชิ้นต่อแพ็ค',
                    },
                  ],
                  allowClear: false,
                },
              ],
              cellType: 'text',
              rowCount: 1,
              minRowCount: 1,
              maxRowCount: 50,
              addRowLocation: 'top',
              addRowText: 'เพิ่มขนาดบรรจุภัณฑ์',
            },
          ],
          title: 'ขนาดบรรจุภัณฑ์',
        },
        {
          type: 'html',
          name: 'divider3',
          html: '<div class="panel-divider"></div>',
        },
        {
          type: 'panel',
          name: 'uploadPanel',
          elements: [
            {
              type: 'file',
              name: 'images',
              title:
                'กรุณาอัปโหลด รูปภาพด้านหน้า ด้านข้าง ด้านหลังของสินค้า โดยท่านสามารถอัปโหลดรูปภาพได้สูงสุดไม่เกิน 5 รูป',
              description: 'ประเภทไฟล์ .jpg, .jpeg, .png (ขนาดรูปไม่เกิน 1 MB)',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณาอัปโหลดรูปภาพ',
              allowMultiple: true,
              acceptedTypes: 'image/png, image/jpeg',
              storeDataAsText: false,
              waitForUpload: true,
              maxSize: 1048576,
              needConfirmRemoveFile: true,
            },
          ],
          title: 'อัปโหลดรูปภาพ',
        },
        {
          type: 'html',
          name: 'divider4',
          html: '<div class="panel-divider"></div>',
        },
        {
          type: 'panel',
          name: 'descPanel',
          elements: [
            {
              type: 'comment',
              name: 'description',
              width: 'fit-content',
              title:
                'อธิบายรายละเอียดสินค้า และจุดเด่น (เช่น ประโยชน์ กลุ่มเป้าหมาย ส่วนประกอบที่โดดเด่น รางวัลที่ได้รับ)',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกอธิบายรายละเอียดของสินค้า และจุดเด่น',
              maxLength: 1000,
              placeholder:
                'อธิบายรายละเอียดสินค้า และจุดเด่น (เช่น ประโยชน์ กลุ่มเป้าหมาย ส่วนประกอบที่โดดเด่น รางวัลที่ได้รับ)',
            },
          ],
          title: 'รายละเอียดของสินค้า (Product Details)',
        },
        {
          type: 'html',
          name: 'divider5',
          html: '<div class="panel-divider"></div>',
        },
        {
          type: 'panel',
          name: 'pricePanel',
          elements: [
            {
              type: 'text',
              name: 'price',
              width: '20%',
              minWidth: '158px',
              title: 'ราคาแนะนำต่อหน่วย',
              placeholder: '0.00',
              hideNumber: true,
              isRequired: true,
              requiredErrorText: 'กรุณากรอกราคาแนะนำต่อหน่วย',
              inputType: 'number',
              validators: [
                {
                  type: 'expression',
                  text: 'ราคาแนะนำต่อหน่วยต้องมากกว่า 0',
                  expression: '{price} > 0',
                },
              ],
            },
            {
              type: 'dropdown',
              name: 'unit',
              width: '15%',
              minWidth: '118px',
              startWithNewLine: false,
              title: 'หน่วย',
              hideNumber: true,
              defaultValue: 'g',
              choices: [
                {
                  value: 'g',
                  text: 'กรัม',
                },
                {
                  value: 'kg',
                  text: 'กิโลกรัม',
                },
                {
                  value: 'ml',
                  text: 'มิลลิลิตร',
                },
                {
                  value: 'l',
                  text: 'ลิตร',
                },
                {
                  value: 'pc',
                  text: 'ชิ้น',
                },
              ],
              placeholder: 'หน่วย',
              allowClear: false,
            },
            {
              type: 'html',
              name: 'empty3',
              width: '65%',
              minWidth: '400px',
              startWithNewLine: false,
              html: '<div class="empty-slot"></div>',
            },
          ],
          title: 'ราคาแนะนำ',
        },
        {
          type: 'html',
          name: 'divider6',
          html: '<div class="panel-divider"></div>',
        },
        // {
        //   type: 'panel',
        //   name: 'standardPanel',
        //   elements: [
        //     {
        //       type: 'panel',
        //       name: 'requiredStandardPanel',
        //       elements: [],
        //       title: 'มาตรฐานที่กฏหมายบังคับ',
        //       description: '*ถ้าคุณมีข้อมูลมาตรฐานสินค้าที่กฏหมายบังคับไม่ครบถ้วน อาจจะมีผลต่อการพิจารณาสินค้าของคุณ',
        //     },
        //     {
        //       type: 'panel',
        //       name: 'optionalStandardPanel',
        //       elements: [
        //         {
        //           type: 'checkbox',
        //           name: 'optionalStandards',
        //           startWithNewLine: false,
        //           title: ' ',
        //           hideNumber: true,
        //           width: '100%',
        //           hideIfChoicesEmpty: true,
        //           choices: [],
        //           colCount: 2,
        //         },
        //       ],
        //       title: 'มาตรฐานที่กฏหมายไม่บังคับ',
        //     },
        //   ],
        //   title: 'มาตรฐานสินค้าที่ได้รับการรับรอง (เลือกได้มากกว่า 1 ข้อ)',
        // },
        {
          type: 'html',
          name: 'divider7',
          html: '<div class="panel-divider"></div>',
        },
        {
          type: 'panel',
          name: 'linkPanel',
          elements: [
            {
              type: 'text',
              name: 'facebook',
              title: 'เฟซบุ๊ค',
              hideNumber: true,
              inputType: 'url',
              maxLength: 2000,
              placeholder: 'https://',
              validators: [
                {
                  type: 'expression',
                  text: 'รูปแบบ url ไม่ถูกต้อง',
                  expression: 'isValidUrl({facebook})',
                },
              ],
            },
            {
              type: 'text',
              name: 'instagram',
              startWithNewLine: false,
              title: 'อินสตาแกรม',
              hideNumber: true,
              inputType: 'url',
              maxLength: 2000,
              placeholder: 'https://',
              validators: [
                {
                  type: 'expression',
                  text: 'รูปแบบ url ไม่ถูกต้อง',
                  expression: 'isValidUrl({instagram})',
                },
              ],
            },
            {
              type: 'text',
              name: 'tiktok',
              startWithNewLine: false,
              title: 'ติ๊กต็อก',
              hideNumber: true,
              inputType: 'url',
              maxLength: 2000,
              placeholder: 'https://',
              validators: [
                {
                  type: 'expression',
                  text: 'รูปแบบ url ไม่ถูกต้อง',
                  expression: 'isValidUrl({tiktok})',
                },
              ],
            },
            {
              type: 'text',
              name: 'website',
              startWithNewLine: false,
              title: 'เว็บไซต์',
              hideNumber: true,
              inputType: 'url',
              maxLength: 2000,
              placeholder: 'https://',
              validators: [
                {
                  type: 'expression',
                  text: 'รูปแบบ url ไม่ถูกต้อง',
                  expression: 'isValidUrl({website})',
                },
              ],
            },
          ],
          title: 'ลิงก์ข้อมูลสินค้าเพิ่มเติม',
        },
      ],
      title: 'เพิ่มข้อมูลสินค้าลงทะเบียน',
    },
  ],
  calculatedValues: [
    {
      name: 'addressTitle',
      expression: "iif({profileType} = 'company', 'ที่อยู่บริษัท', 'ที่อยู่')",
    },
  ],
  showQuestionNumbers: 'off',
  questionErrorLocation: 'bottom',
  completeText: 'บันทึก',
  pageNextText: 'ถัดไป',
  pagePrevText: 'ย้อนกลับ',
  showCompletedPage: false,
}
